import type { RealtimeOption } from './realtimeOptions.js';

export const GEMINI_VOICES: RealtimeOption[] = [
    {
        id: 'Zephyr',
        name: 'Zephyr',
        description: 'Bright, Higher pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Zephyr.wav',
    },
    {
        id: 'Puck',
        name: 'Puck',
        description: 'Upbeat, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Puck.wav',
    },
    {
        id: 'Charon',
        name: 'Charon',
        description: 'Informative, Lower pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Charon.wav',
    },
    {
        id: 'Kore',
        name: 'Kore',
        description: 'Firm, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Kore.wav',
    },
    {
        id: 'Fenrir',
        name: 'Fenrir',
        description: 'Excitable, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Fenrir.wav',
    },
    {
        id: 'Leda',
        name: 'Leda',
        description: 'Youthful, Higher pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Leda.wav',
    },
    {
        id: 'Orus',
        name: 'Orus',
        description: 'Firm, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Orus.wav',
    },
    {
        id: 'Aoede',
        name: 'Aoede',
        description: 'Breezy, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Aoede.wav',
    },
    {
        id: 'Callirrhoe',
        name: 'Callirrhoe',
        description: 'Easy-going, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Callirrhoe.wav',
    },
    {
        id: 'Autonoe',
        name: 'Autonoe',
        description: 'Bright, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Autonoe.wav',
    },
    {
        id: 'Enceladus',
        name: 'Enceladus',
        description: 'Breathy, Lower pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Enceladus.wav',
    },
    {
        id: 'Iapetus',
        name: 'Iapetus',
        description: 'Clear, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Iapetus.wav',
    },
    {
        id: 'Umbriel',
        name: 'Umbriel',
        description: 'Easy-going, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Umbriel.wav',
    },
    {
        id: 'Algieba',
        name: 'Algieba',
        description: 'Smooth, Lower pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Algieba.wav',
    },
    {
        id: 'Despina',
        name: 'Despina',
        description: 'Smooth, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Despina.wav',
    },
    {
        id: 'Erinome',
        name: 'Erinome',
        description: 'Clear, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Erinome.wav',
    },
    {
        id: 'Algenib',
        name: 'Algenib',
        description: 'Gravelly, Lower pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Algenib.wav',
    },
    {
        id: 'Rasalgethi',
        name: 'Rasalgethi',
        description: 'Informative, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Rasalgethi.wav',
    },
    {
        id: 'Laomedeia',
        name: 'Laomedeia',
        description: 'Upbeat, Higher pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Laomedeia.wav',
    },
    {
        id: 'Achernar',
        name: 'Achernar',
        description: 'Soft, Higher pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Achernar.wav',
    },
    {
        id: 'Alnilam',
        name: 'Alnilam',
        description: 'Firm, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Alnilam.wav',
    },
    {
        id: 'Schedar',
        name: 'Schedar',
        description: 'Even, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Schedar.wav',
    },
    {
        id: 'Gacrux',
        name: 'Gacrux',
        description: 'Mature, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Gacrux.wav',
    },
    {
        id: 'Pulcherrima',
        name: 'Pulcherrima',
        description: 'Forward, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Pulcherrima.wav',
    },
    {
        id: 'Achird',
        name: 'Achird',
        description: 'Friendly, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Achird.wav',
    },
    {
        id: 'Zubenelgenubi',
        name: 'Zubenelgenubi',
        description: 'Casual, Lower middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Zubenelgenubi.wav',
    },
    {
        id: 'Vindemiatrix',
        name: 'Vindemiatrix',
        description: 'Gentle, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Vindemiatrix.wav',
    },
    {
        id: 'Sadachbia',
        name: 'Sadachbia',
        description: 'Lively, Lower pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Sadachbia.wav',
    },
    {
        id: 'Sadaltager',
        name: 'Sadaltager',
        description: 'Knowledgeable, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Sadaltager.wav',
    },
    {
        id: 'Sulafat',
        name: 'Sulafat',
        description: 'Warm, Middle pitch',
        previewUrl: 'https://gstatic.com/aistudio/voices/samples/Sulafat.wav',
    },
];
