export type PipelineModelOption = {
    id: string;
    name: string;
    description?: string;
    /**
     * Default voice id to seed `engine.voice_id` in pipeline mode.
     */
    defaultVoiceId?: string;
    /**
     * Supported language codes for this model (ISO-639-1 in most cases; some providers
     * may use provider-specific codes as documented by LiveKit Inference).
     */
    languages?: string[];
};

export type PipelineProviderModels = {
    providerId: string;
    displayName: string;
    models: PipelineModelOption[];
};

type PipelineOptionsResponse = {
    stt: PipelineProviderModels[];
    tts: PipelineProviderModels[];
    llm: PipelineProviderModels[];
};

export function getPipelineOptions(): PipelineOptionsResponse {
    // Sources for model language support:
    // - https://docs.livekit.io/agents/models/stt/inference/assemblyai/
    // - https://docs.livekit.io/agents/models/stt/inference/cartesia/
    // - https://docs.livekit.io/agents/models/stt/inference/deepgram/
    // - https://docs.livekit.io/agents/models/stt/inference/elevenlabs/
    // - https://docs.livekit.io/agents/models/stt/plugins/sarvam/
    const ASSEMBLYAI_UNIVERSAL_LANGUAGES = ['en', 'en-US'];
    const ASSEMBLYAI_MULTILINGUAL_LANGUAGES = [
        'en',
        'en-US',
        'en-GB',
        'en-AU',
        'en-CA',
        'en-IN',
        'en-NZ',
        'es',
        'es-ES',
        'es-MX',
        'es-AR',
        'es-CO',
        'es-CL',
        'es-PE',
        'es-VE',
        'es-EC',
        'es-GT',
        'es-CU',
        'es-BO',
        'es-DO',
        'es-HN',
        'es-PY',
        'es-SV',
        'es-NI',
        'es-CR',
        'es-PA',
        'es-UY',
        'es-PR',
        'fr',
        'fr-FR',
        'fr-CA',
        'fr-BE',
        'fr-CH',
        'de',
        'de-DE',
        'de-AT',
        'de-CH',
        'it',
        'it-IT',
        'it-CH',
        'pt',
        'pt-BR',
        'pt-PT',
    ];
    const CARTESIA_INK_WHISPER_LANGUAGES = [
        'en',
        'zh',
        'ar',
        'de',
        'es',
        'ru',
        'ko',
        'fr',
        'ja',
        'pt',
        'tr',
        'pl',
        'ca',
        'nl',
        'sv',
        'it',
        'id',
        'vi',
        'he',
        'hi',
        'uk',
        'el',
        'ms',
        'cs',
        'ro',
        'da',
        'hu',
        'ta',
        'no',
        'th',
        'ur',
        'hr',
        'bg',
        'lt',
        'la',
        'mi',
        'ml',
        'cy',
        'sk',
        'te',
        'fa',
        'fi',
        'lv',
        'bn',
        'sr',
        'az',
        'sl',
        'kn',
        'et',
        'mk',
        'br',
        'eu',
        'is',
        'hy',
        'ne',
        'mn',
        'bs',
        'kk',
        'sq',
        'sw',
        'gl',
        'mr',
        'pa',
        'si',
        'km',
        'sn',
        'yo',
        'so',
        'af',
        'oc',
        'ka',
        'be',
        'tg',
        'sd',
        'gu',
        'am',
        'yi',
        'lo',
        'uz',
        'fo',
        'ht',
        'ps',
        'tk',
        'nn',
        'mt',
        'sa',
        'lb',
        'my',
        'bo',
        'tl',
        'mg',
        'as',
        'tt',
        'haw',
        'ln',
        'ha',
        'ba',
        'jw',
        'su',
        'yue',
    ];
    const DEEPGRAM_ENGLISH_ONLY = ['en'];
    const DEEPGRAM_ENGLISH_EN_US = ['en', 'en-US'];
    const DEEPGRAM_NOVA_3_LANGUAGES = [
        'ar',
        'ar-AE',
        'ar-SA',
        'ar-QA',
        'ar-KW',
        'ar-SY',
        'ar-LB',
        'ar-PS',
        'ar-JO',
        'ar-EG',
        'ar-SD',
        'ar-TD',
        'ar-MA',
        'ar-DZ',
        'ar-TN',
        'ar-IQ',
        'ar-IR',
        'en',
        'en-US',
        'en-AU',
        'en-GB',
        'en-IN',
        'en-NZ',
        'de',
        'nl',
        'sv',
        'sv-SE',
        'da',
        'da-DK',
        'es',
        'es-419',
        'fr',
        'fr-CA',
        'pt',
        'pt-BR',
        'pt-PT',
        'multi',
    ];
    const DEEPGRAM_NOVA_3_MEDICAL_LANGUAGES = [
        'en',
        'en-US',
        'en-AU',
        'en-CA',
        'en-GB',
        'en-IE',
        'en-IN',
        'en-NZ',
    ];
    const DEEPGRAM_NOVA_2_LANGUAGES = [
        'multi',
        'bg',
        'ca',
        'zh',
        'zh-CN',
        'zh-Hans',
        'zh-TW',
        'zh-Hant',
        'zh-HK',
        'cs',
        'da',
        'da-DK',
        'nl',
        'en',
        'en-US',
        'en-AU',
        'en-GB',
        'en-NZ',
        'en-IN',
        'et',
        'fi',
        'nl-BE',
        'fr',
        'fr-CA',
        'de',
        'de-CH',
        'el',
        'hi',
        'hu',
        'id',
        'it',
        'ja',
        'ko',
        'ko-KR',
        'lv',
        'lt',
        'ms',
        'no',
        'pl',
        'pt',
        'pt-BR',
        'pt-PT',
        'ro',
        'ru',
        'sk',
        'es',
        'es-419',
        'sv',
        'sv-SE',
        'th',
        'th-TH',
        'tr',
        'uk',
        'vi',
    ];
    const ELEVENLABS_SCRIBE_V2_LANGUAGES = [
        'en',
        'en-US',
        'en-GB',
        'en-AU',
        'en-CA',
        'en-IN',
        'en-NZ',
        'es',
        'es-ES',
        'es-MX',
        'es-AR',
        'es-CO',
        'es-CL',
        'es-PE',
        'es-VE',
        'es-EC',
        'es-GT',
        'es-CU',
        'es-BO',
        'es-DO',
        'es-HN',
        'es-PY',
        'es-SV',
        'es-NI',
        'es-CR',
        'es-PA',
        'es-UY',
        'es-PR',
        'fr',
        'fr-FR',
        'fr-CA',
        'fr-BE',
        'fr-CH',
        'de',
        'de-DE',
        'de-AT',
        'de-CH',
        'it',
        'it-IT',
        'it-CH',
        'pt',
        'pt-BR',
        'pt-PT',
        'pl',
        'pl-PL',
        'ru',
        'ru-RU',
        'ja',
        'ja-JP',
        'zh',
        'zh-CN',
        'zh-TW',
        'zh-HK',
        'ko',
        'ko-KR',
        'ar',
        'ar-SA',
        'ar-EG',
        'ar-AE',
        'ar-IQ',
        'ar-DZ',
        'ar-MA',
        'ar-KW',
        'ar-JO',
        'ar-LB',
        'ar-OM',
        'ar-QA',
        'ar-BH',
        'ar-TN',
        'ar-YE',
        'ar-SY',
        'ar-SD',
        'ar-LY',
        'ar-MR',
        'ar-SO',
        'ar-DJ',
        'ar-KM',
        'ar-ER',
        'ar-TD',
        'hi',
        'hi-IN',
        'tr',
        'tr-TR',
        'nl',
        'nl-NL',
        'nl-BE',
        'sv',
        'sv-SE',
        'id',
        'id-ID',
        'cs',
        'cs-CZ',
        'ro',
        'ro-RO',
        'hu',
        'hu-HU',
        'fi',
        'fi-FI',
        'da',
        'da-DK',
        'no',
        'no-NO',
        'th',
        'th-TH',
        'vi',
        'vi-VN',
        'uk',
        'uk-UA',
        'el',
        'el-GR',
        'he',
        'he-IL',
        'ms',
        'ms-MY',
        'sk',
        'sk-SK',
        'hr',
        'hr-HR',
        'bg',
        'bg-BG',
        'sr',
        'sr-RS',
        'sl',
        'sl-SI',
        'et',
        'et-EE',
        'lv',
        'lv-LV',
        'lt',
        'lt-LT',
        'is',
        'is-IS',
        'ga',
        'ga-IE',
        'mt',
        'mt-MT',
        'cy',
        'cy-GB',
    ];
    const SARVAM_SAARIKA_V25_LANGUAGES = [
        'bn-IN',
        'en-IN',
        'gu-IN',
        'hi-IN',
        'kn-IN',
        'ml-IN',
        'mr-IN',
        'od-IN',
        'pa-IN',
        'ta-IN',
        'te-IN',
    ];

    return {
        stt: [
            {
                providerId: 'assemblyai',
                displayName: 'AssemblyAI',
                models: [
                    {
                        id: 'assemblyai/universal-streaming:en',
                        name: 'AssemblyAI Universal-Streaming (EN)',
                        languages: ASSEMBLYAI_UNIVERSAL_LANGUAGES,
                    },
                    {
                        id: 'assemblyai/universal-streaming-multilingual:en',
                        name: 'AssemblyAI Universal-Streaming Multilingual',
                        languages: ASSEMBLYAI_MULTILINGUAL_LANGUAGES,
                    },
                ],
            },
            {
                providerId: 'cartesia',
                displayName: 'Cartesia',
                models: [
                    {
                        id: 'cartesia/ink-whisper:en',
                        name: 'Cartesia Ink Whisper (EN)',
                        languages: CARTESIA_INK_WHISPER_LANGUAGES,
                    },
                ],
            },
            {
                providerId: 'deepgram',
                displayName: 'Deepgram',
                models: [
                    {
                        id: 'deepgram/flux-general:en',
                        name: 'Deepgram Flux (EN)',
                        languages: DEEPGRAM_ENGLISH_ONLY,
                    },
                    {
                        id: 'deepgram/nova-3:en',
                        name: 'Deepgram Nova-3 (EN)',
                        languages: DEEPGRAM_NOVA_3_LANGUAGES,
                    },
                    {
                        id: 'deepgram/nova-3:multi',
                        name: 'Deepgram Nova-3 (Multilingual)',
                        languages: DEEPGRAM_NOVA_3_LANGUAGES,
                    },
                    {
                        id: 'deepgram/nova-3-medical:en',
                        name: 'Deepgram Nova-3 Medical (EN)',
                        languages: DEEPGRAM_NOVA_3_MEDICAL_LANGUAGES,
                    },
                    {
                        id: 'deepgram/nova-2:en',
                        name: 'Deepgram Nova-2 (EN)',
                        languages: DEEPGRAM_NOVA_2_LANGUAGES,
                    },
                    {
                        id: 'deepgram/nova-2:multi',
                        name: 'Deepgram Nova-2 (Multilingual)',
                        languages: DEEPGRAM_NOVA_2_LANGUAGES,
                    },
                    {
                        id: 'deepgram/nova-2-medical:en',
                        name: 'Deepgram Nova-2 Medical (EN)',
                        languages: DEEPGRAM_ENGLISH_EN_US,
                    },
                    {
                        id: 'deepgram/nova-2-conversationalai:en',
                        name: 'Deepgram Nova-2 Conversational AI (EN)',
                        languages: DEEPGRAM_ENGLISH_EN_US,
                    },
                    {
                        id: 'deepgram/nova-2-phonecall:en',
                        name: 'Deepgram Nova-2 Phonecall (EN)',
                        languages: DEEPGRAM_ENGLISH_EN_US,
                    },
                ],
            },
            {
                providerId: 'elevenlabs',
                displayName: 'ElevenLabs',
                models: [
                    {
                        id: 'elevenlabs/scribe_v2_realtime:en',
                        name: 'ElevenLabs Scribe V2 Realtime (EN)',
                        languages: ELEVENLABS_SCRIBE_V2_LANGUAGES,
                    },
                ],
            },
            {
                providerId: 'sarvam',
                displayName: 'Sarvam',
                models: [
                    {
                        id: 'sarvam/saarika:v2.5',
                        name: 'Sarvam Saarika v2.5',
                        languages: SARVAM_SAARIKA_V25_LANGUAGES,
                    },
                ],
            },
        ],
        tts: [
            {
                providerId: 'cartesia',
                displayName: 'Cartesia',
                models: [
                    {
                        id: 'cartesia/sonic-3',
                        name: 'Cartesia Sonic-3',
                        defaultVoiceId: '9626c31c-bec5-4cca-baa8-f8ba9e84c8bc',
                    },
                    {
                        id: 'cartesia/sonic-2',
                        name: 'Cartesia Sonic-2',
                        defaultVoiceId: '9626c31c-bec5-4cca-baa8-f8ba9e84c8bc',
                    },
                    {
                        id: 'cartesia/sonic-turbo',
                        name: 'Cartesia Sonic-Turbo',
                        defaultVoiceId: '9626c31c-bec5-4cca-baa8-f8ba9e84c8bc',
                    },
                    {
                        id: 'cartesia/sonic',
                        name: 'Cartesia Sonic',
                        defaultVoiceId: '9626c31c-bec5-4cca-baa8-f8ba9e84c8bc',
                    },
                ],
            },
            {
                providerId: 'deepgram',
                displayName: 'Deepgram',
                models: [
                    {
                        id: 'deepgram/aura-2',
                        name: 'Deepgram Aura-2',
                        defaultVoiceId: 'athena',
                    },
                ],
            },
            {
                providerId: 'elevenlabs',
                displayName: 'ElevenLabs',
                models: [
                    {
                        id: 'elevenlabs/eleven_flash_v2',
                        name: 'ElevenLabs Eleven Flash v2',
                        defaultVoiceId: 'Xb7hH8MSUJpSbSDYk0k2',
                    },
                    {
                        id: 'elevenlabs/eleven_flash_v2_5',
                        name: 'ElevenLabs Eleven Flash v2.5',
                        defaultVoiceId: 'Xb7hH8MSUJpSbSDYk0k2',
                    },
                    {
                        id: 'elevenlabs/eleven_turbo_v2',
                        name: 'ElevenLabs Eleven Turbo v2',
                        defaultVoiceId: 'Xb7hH8MSUJpSbSDYk0k2',
                    },
                    {
                        id: 'elevenlabs/eleven_turbo_v2_5',
                        name: 'ElevenLabs Eleven Turbo v2.5',
                        defaultVoiceId: 'Xb7hH8MSUJpSbSDYk0k2',
                    },
                    {
                        id: 'elevenlabs/eleven_multilingual_v2',
                        name: 'ElevenLabs Eleven Multilingual v2',
                        defaultVoiceId: 'Xb7hH8MSUJpSbSDYk0k2',
                    },
                ],
            },
            {
                providerId: 'inworld',
                displayName: 'Inworld',
                models: [
                    {
                        id: 'inworld/inworld-tts-1.5-max',
                        name: 'Inworld TTS 1.5 Max',
                        defaultVoiceId: 'Ashley',
                    },
                    {
                        id: 'inworld/inworld-tts-1.5-mini',
                        name: 'Inworld TTS 1.5 Mini',
                        defaultVoiceId: 'Ashley',
                    },
                    {
                        id: 'inworld/inworld-tts-1-max',
                        name: 'Inworld TTS-1 Max',
                        defaultVoiceId: 'Ashley',
                    },
                    {
                        id: 'inworld/inworld-tts-1',
                        name: 'Inworld TTS-1',
                        defaultVoiceId: 'Ashley',
                    },
                ],
            },
            {
                providerId: 'rime',
                displayName: 'Rime',
                models: [
                    {
                        id: 'rime/arcana',
                        name: 'Rime Arcana V2',
                        defaultVoiceId: 'astra',
                    },
                    {
                        id: 'rime/mistv2',
                        name: 'Rime Mist V2',
                        defaultVoiceId: 'astra',
                    },
                ],
            },
            {
                providerId: 'sarvam',
                displayName: 'Sarvam',
                models: [
                    {
                        id: 'sarvam/bulbul:v3',
                        name: 'Sarvam Bulbul v3',
                        defaultVoiceId: 'shubh',
                        languages: [
                            'bn-IN',
                            'en-IN',
                            'gu-IN',
                            'hi-IN',
                            'kn-IN',
                            'ml-IN',
                            'mr-IN',
                            'od-IN',
                            'pa-IN',
                            'ta-IN',
                            'te-IN',
                        ],
                    },
                ],
            },
        ],
        llm: [
            {
                providerId: 'openai',
                displayName: 'OpenAI',
                models: [
                    { id: 'openai/gpt-4o-mini', name: 'GPT-4o Mini' },
                    { id: 'openai/gpt-4o', name: 'GPT-4o' },
                    { id: 'openai/gpt-4.1', name: 'GPT-4.1' },
                    { id: 'openai/gpt-4.1-mini', name: 'GPT-4.1 Mini' },
                    { id: 'openai/gpt-4.1-nano', name: 'GPT-4.1 Nano' },
                    { id: 'openai/gpt-5', name: 'GPT-5' },
                    { id: 'openai/gpt-5-mini', name: 'GPT-5 Mini' },
                    { id: 'openai/gpt-5-nano', name: 'GPT-5 Nano' },
                    { id: 'openai/gpt-5.1', name: 'GPT-5.1' },
                    { id: 'openai/gpt-5.1-chat-latest', name: 'GPT-5.1 Chat Latest' },
                    { id: 'openai/gpt-5.2', name: 'GPT-5.2' },
                    { id: 'openai/gpt-5.2-chat-latest', name: 'GPT-5.2 Chat Latest' },
                    { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B' },
                ],
            },
            {
                providerId: 'google',
                displayName: 'Google Gemini',
                models: [
                    { id: 'google/gemini-3-flash', name: 'Gemini 3 Flash' },
                    { id: 'google/gemini-3-pro', name: 'Gemini 3 Pro' },
                    { id: 'google/gemini-2.5-flash', name: 'Gemini 2.5 Flash' },
                    { id: 'google/gemini-2.5-pro', name: 'Gemini 2.5 Pro' },
                    { id: 'google/gemini-2.5-flash-lite', name: 'Gemini 2.5 Flash Lite' },
                    { id: 'google/gemini-2.0-flash', name: 'Gemini 2.0 Flash' },
                    { id: 'google/gemini-2.0-flash-lite', name: 'Gemini 2.0 Flash Lite' },
                ],
            },
            {
                providerId: 'qwen',
                displayName: 'Qwen',
                models: [
                    {
                        id: 'qwen/qwen3-235b-a22b-instruct',
                        name: 'Qwen3 235B Instruct',
                    },
                ],
            },
            {
                providerId: 'moonshotai',
                displayName: 'MoonshotAI (Kimi)',
                models: [{ id: 'moonshotai/kimi-k2-instruct', name: 'Kimi K2 Instruct' }],
            },
            {
                providerId: 'deepseek-ai',
                displayName: 'DeepSeek',
                models: [
                    { id: 'deepseek-ai/deepseek-v3', name: 'DeepSeek V3' },
                    { id: 'deepseek-ai/deepseek-v3.2', name: 'DeepSeek V3.2' },
                ],
            },
        ],
    };
}
